"use strict";
//import * as Vector from 'flo-vector2d';
Object.defineProperty(exports, "__esModule", { value: true });
const draw_elem_1 = require("./draw-elem/draw-elem");
class BezDebug {
    /**
     * @param config - configuration settings.
     * @param fs - some useful functions.
     * @private
     */
    constructor(draw, g) {
        //(this as any).Bezier3 = Bezier3; // Included only for quick debugging from console
        //(this as any).Vector2d = Vector; // ...
        this.draw = draw;
        this.g = g;
        //-----------------------------------------------
        // Generated by debug object for later inspection
        //-----------------------------------------------
        this.generated = {
            elems: {
                beziers: [],
                fatLine: [],
                looseBoundingBox: [],
                tightBoundingBox: [],
                extreme: [],
                boundingHull: [],
                intersection: [],
            }
        };
        this.fs = {
            draw,
            drawElem: draw_elem_1.drawElemFunctions,
        };
    }
}
exports.BezDebug = BezDebug;
//# sourceMappingURL=debug.js.map