declare function γ(n: number): number;
declare function γγ(n: number): number;
declare const γ1: number;
declare const γ2: number;
declare const γ3: number;
declare const γ4: number;
declare const γ5: number;
declare const γ6: number;
declare const γ7: number;
declare const γ8: number;
declare const γ9: number;
declare const γ10: number;
declare const γ11: number;
declare const γ12: number;
declare const γ13: number;
declare const γ14: number;
declare const γγ1: number;
declare const γγ2: number;
declare const γγ3: number;
declare const γγ4: number;
declare const γγ5: number;
declare const γγ6: number;
declare const γγ7: number;
declare const γγ8: number;
declare const γγ9: number;
declare const γγ10: number;
declare const γγ11: number;
declare const γγ12: number;
declare const γγ13: number;
declare const γγ14: number;
export { γ, γ1, γ2, γ3, γ4, γ5, γ6, γ7, γ8, γ9, γ10, γ11, γ12, γ13, γ14, γγ, γγ1, γγ2, γγ3, γγ4, γγ5, γγ6, γγ7, γγ8, γγ9, γγ10, γγ11, γγ12, γγ13, γγ14 };
