const vectorsBoolean = [
    'two-simple',
    'lamina',
    'koldat52-over-square',
    'two-squares',
    'three-squares',
    'one-square-inside-a',
    'one-square-inside-b',
    'two-squares-inside',
    'one-square-inside-lamina',
    'two-squares-inside-lamina',
    'lamina-inside-square'
];
const vectors = [
    // 'two-circles-1',
    'sq-in-sq-in-sq-in-sq',
    'sq-in-sq-in-sq-in-sq-2',
    // 'AA',
    // "play3",
    'at',
    'complex-min',
    'orient',
    'orient2',
    'comp',
    'con-squares',
    'koldatter',
    // 'koldatter2',
    'three-squares',
    'four-squares',
    'five-squares',
    'confuse1',
    'confuse2',
    'two-squares',
    'snuggle-1',
    'complex6',
    'woodland2',
    'woodland',
    'complex4',
    'complex3',
    'koldat-again',
    'complex',
    'complex2',
    'multi-level-reversed-orientation',
    'multi-level-reversed-orientation2',
    'quad-blob',
    'horight-o',
    'koldat52-over-square-2',
    'same-k-family-lines-2',
    'koldat52-over-square',
    'few-xs-at-min-y',
    'multiple-xs-at-min-y',
    'complexish',
    'complexish2',
    'complexish3',
    'complexish4',
    'koldat51',
    'koldat52',
    'koldat53',
    'koldat54',
    'koldat55',
    'koldat56',
    'p',
    'topmost-no-interface',
    'ring2',
    'V2',
    'Mt44',
    'new1',
    'new2',
    'bold-b',
    'square',
    'B',
    'same-k-family-lines',
    'holy-poly',
    'f',
    'split-shape-lines',
    'tiny-min-y-loop'
];
export { vectors, vectorsBoolean };
//# sourceMappingURL=vectors.js.map